// this file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise'
import { OpenAPI } from './core/OpenAPI'
import { request as __request } from './core/request'
import type {
  GetActivitiesResponse,
  PostFavoritesData,
  PostFavoritesResponse,
} from './types.gen'

export class DefaultService {
  /**
   * get all activities
   * @returns unknown A list of activities
   * @throws ApiError
   */
  public static getActivities(): CancelablePromise<GetActivitiesResponse> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/activities',
    })
  }

  /**
   * add an activity to favorites
   * @param data The data for the request.
   * @param data.requestBody
   * @returns unknown Favorite added
   * @throws ApiError
   */
  public static postFavorites(
    data: PostFavoritesData,
  ): CancelablePromise<PostFavoritesResponse> {
    return __request(OpenAPI, {
      method: 'POST',
      url: '/favorites',
      body: data.requestBody,
      mediaType: 'application/json',
      errors: {
        400: 'Invalid request',
      },
    })
  }
}
