// this file is auto-generated by @hey-api/openapi-ts

export type GetActivitiesResponse = Array<{
  id?: number
  photoUrl?: string
  name?: string
  description?: string
  location?: string
  price?: number
  rating?: number
}>

export type PostFavoritesData = {
  requestBody: {
    id: number
  }
}

export type PostFavoritesResponse = {
  message?: string
}

export type $OpenApiTs = {
  '/activities': {
    get: {
      res: {
        /**
         * a list of activities
         */
        200: Array<{
          id?: number
          photoUrl?: string
          name?: string
          description?: string
          location?: string
          price?: number
          rating?: number
        }>
      }
    }
  }
  '/favorites': {
    post: {
      req: PostFavoritesData
      res: {
        /**
         * favorite added
         */
        200: {
          message?: string
        }
        /**
         * invalid request
         */
        400: {
          error?: string
        }
      }
    }
  }
}
